spring.application.name=SB-SMS
# embedded tomcat server
server.port = 1100
#Database Properties
spring.datasource.url=jdbc:mysql://localhost:3306/suppliers
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

sms.save.success = "SUCCESS : Supplier Object Saved"
sms.db.fail = "FAILED : DB Error"

sms.update.success = "SUCCESS : Supplier Object Updated"
sms.db.fail = "FAILED : DB Error"

sms.delete.success = "SUCCESS : Supplier Object Deleted"
sms.db.fail = "FAILED : DB Error"

sms.findid.success = "SUCCESS : Supplier Object Found"
sms.db.fail = "FAILED : DB Error"

ems.findAll.success = "SUCCESS : Supplier Objects Found"
ems.db.fail = "FAILED : DB Error"

#application error properties
sms.invalid.supplier-details = "FAILED : Invalid Supplier Details"
sms.invalid.supplier-notFound = "FAILED : Supplier Not Found



eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true